server:
  port: 8084

spring:
  application:
    name: GATEWAY_SERVICE_FOR_APIs
    
  cloud:
    config:
      discovery:
        enabled: true # This is required
        service-id: CONFIG-SERVER # Config Server's eureka registry name
      enabled: true 
    gateway:
      routes:
        - id: MICROSERVICE-CUSTOMERS
          uri: lb://MICROSERVICE-CUSTOMERS
          predicates:
            - Path=/customer/**
        - id: MICROSERVICE-ACCOUNTS
          uri: lb://MICROSERVICE-ACCOUNTS
          predicates:
            - Path=/**
        

eureka:
  instance:
    prefer-ip-address: true
  hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka